# Generated by Django 4.0.5 on 2022-07-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='data',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
