# Generated by Django 4.0.5 on 2022-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='prc',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='tkn',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='vol',
            field=models.JSONField(),
        ),
    ]
