# Generated by Django 4.0.5 on 2022-07-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFT', '0002_alter_datapoint_prc_alter_datapoint_tkn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='prc',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='tkn',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='vol',
            field=models.JSONField(default={}),
        ),
    ]
